import type { TabConfig } from "./tabbedAccordion.types";

/**
 * Demo names for development. Replace with `tabs` from your API or app state in production.
 */
export const DEMO_TAB_GROUPS: readonly [
  readonly string[],
  readonly string[],
  readonly string[],
] = [
  [
    "Anna Mitchell",
    "Thomas Bennett",
    "Iris Castellan",
    "Otto Duarte",
    "Louise Evans",
    "Henry Farrell",
    "Amelia Gordon",
    "Dwight Harrison",
    "Constance Ingalls",
    "Simon Jordan",
    "Rafael Keller",
    "Eleanor Matos",
    "Martin Noble",
    "Olivia Ornelas",
    "Peter Paulson",
    "Kayla Ramos",
    "Rodrigo Silver",
    "Susan Tavares",
    "Telmo Umbelino",
    "Uri Vilalta",
  ],
  [
    "Beatrice Lemos",
    "Michael Macedo",
    "Natalie Neves",
    "Alexander Oliveira",
    "Patricia Pires",
    "Richard Queen",
    "Sarah Rivers",
    "Timothy Sequeira",
    "Uma Tavares",
    "Victor Ulrich",
    "Wilma Zanetti",
    "Adrian Azenha",
    "Brian Borges",
    "Cathy Cruz",
    "Danielle Domingos",
    "Edward Estrella",
    "Philippe Fonseca",
    "Grant Gil",
    "Helen Horta",
    "Ian Innocente",
  ],
  [
    "Williams Abreu",
    "Xenia Barros",
    "Yago Calder",
    "Zara Dennis",
    "Alan Esteves",
    "Berta Freitas",
    "Cesar Gusmao",
    "Dalila Horta",
    "Erica Inacio",
    "Fabricio Jacques",
    "Gilda Krieger",
    "Horacio Lopes",
    "Isabel Mota",
    "James Noronha",
    "Kelly Oliva",
    "Lucio Peralta",
    "Martha Quental",
    "Nuno Rebelo",
    "Odete Salvado",
    "Paula Tereno",
  ],
];

/** Demo config with three tabs (labels + rows); use as reference or pass via `tabs`. */
export const DEFAULT_TAB_CONFIG: TabConfig[] = [
  { label: "Tab 1", row: DEMO_TAB_GROUPS[0], maxItems: 20 },
  { label: "Tab 2", row: DEMO_TAB_GROUPS[1], maxItems: 15 },
  { label: "Tab 3", row: DEMO_TAB_GROUPS[2] },
];
