import type { TabConfig } from "./tabbedAccordion.types";

/**
 * Dados de demonstração (nomes). Trocar por `tabs` vinda de API/estado no `App` em produção.
 */
export const DEMO_TAB_GROUPS: readonly [
  readonly string[],
  readonly string[],
  readonly string[],
] = [
  [
    "Marina Alcântara",
    "Tomás Bettencourt",
    "Íris Castelo",
    "Otávio Duarte",
    "Luísa Esteves",
    "Henrique Faria",
    "Amélia Gouveia",
    "Duarte Henriques",
    "Constança Inácio",
    "Simão Jordão",
    "Rafael Keller",
    "Leonor Matos",
    "Martinho Nobre",
    "Olívia Ornelas",
    "Pedro Paulino",
    "Queila Ramos",
    "Rodrigo Silvestre",
    "Susana Tavares",
    "Telmo Umbelino",
    "Urano Vilalta",
  ],
  [
    "Beatriz Lemos",
    "Miguel Macedo",
    "Natália Neves",
    "Alexandre Oliveira",
    "Patrícia Pires",
    "Ricardo Queiroz",
    "Sara Ribeiro",
    "Tiago Sequeira",
    "Úrsula Tavares",
    "Vasco Ulrich",
    "Wilma Zanetti",
    "Adriana Azenha",
    "Bruno Borges",
    "Cátia Cruz",
    "Daniela Domingos",
    "Eduardo Estrela",
    "Filipa Fonseca",
    "Gonçalo Gil",
    "Helena Horta",
    "Ivo Inocêncio",
  ],
  [
    "Williams Abreu",
    "Xenia Barros",
    "Yago Caldeira",
    "Zara Dinis",
    "Alan Esteves",
    "Berta Freitas",
    "César Gusmão",
    "Dalila Horta",
    "Érica Inácio",
    "Fabrício Jaques",
    "Gilda Krieger",
    "Horácio Lopes",
    "Isabel Mota",
    "Jaime Noronha",
    "Kelly Oliva",
    "Lúcio Peralta",
    "Marta Quental",
    "Nuno Rebelo",
    "Odete Salvado",
    "Paula Tereno",
  ],
];

/** Config demo de 3 abas (rótulos + linhas); usar como referência ou passar em `tabs`. */
export const DEFAULT_TAB_CONFIG: TabConfig[] = [
  { label: "Aba 1", row: DEMO_TAB_GROUPS[0], maxItems: 20 },
  { label: "Aba 2", row: DEMO_TAB_GROUPS[1], maxItems: 15 },
  { label: "Aba 3", row: DEMO_TAB_GROUPS[2] },
];
